approach_name: '3'
pos_emb_dim: 0
softmax_temp: 1
injection_info: [   # list of lists
  [3, 3, 3] # [InjectionLayer,NumStack,FilterSize]
]
padding: same
stride: 1
apply_stochastic_stride: False
use_residual_connection: False
suffix: FixedPad
random_k: -1
