approach_name: '3_unmasked'
pos_emb_dim: 0
softmax_temp: 1
injection_info: [   # list of lists
  [3, 1, 3] # [InjectionLayer,NumStack,FilterSize]
]
padding: same
stride: 1
apply_stochastic_stride: False
use_residual_connection: False
random_k: -1
forget_gate_nonlinearity: 'sigmoid'
similarity_metric: 'cosine_similarity'
