name: '3'
pos_emb_dim: 0
softmax_temp: 1
injection_info: [   # list of lists
  [2, 1, 3], # [InjectionLayer,NumStack,FilterSize,PadType]
  # [3, 1, 3],
  [4, 1, 3],
  [5, 1, 3],
  # [5, 1, 3]
]
padding: same
stride: 1
apply_stochastic_stride: False
suffix: FixedPad